import json
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

COMPLIANCE_FRAMEWORK = {
    'NIST_SSDF': {
        'name': 'NIST Secure Software Development Framework (SSDF)',
        'version': 'SP 800-218',
        'controls': [
            {
                'id': 'PW.4',
                'title': 'Reuse Existing, Well-Secured Software',
                'description': 'Acquire and maintain well-secured software components from trusted sources.',
                'status': 'VIOLATED',
                'reason': 'Unauthorized dependency changes detected in runtime environment not present in approved baseline.',
                'triggered_by': ['added', 'changed']
            },
            {
                'id': 'PO.3',
                'title': 'Implement Supporting Toolchains',
                'description': 'Use automated toolchains to generate and verify SBOMs throughout the software lifecycle.',
                'status': 'PARTIAL',
                'reason': 'SBOM generated at build time but runtime validation gap detected.',
                'triggered_by': ['any']
            },
            {
                'id': 'RV.1',
                'title': 'Identify and Confirm Vulnerabilities',
                'description': 'Identify and confirm vulnerabilities on an ongoing basis.',
                'status': 'VIOLATED',
                'reason': 'Runtime dependency changes introduced packages with known CVEs without detection.',
                'triggered_by': ['changed']
            }
        ]
    },
    'CIS_DOCKER': {
        'name': 'CIS Docker Benchmark',
        'version': 'v1.6.0',
        'controls': [
            {
                'id': '4.1',
                'title': 'Ensure a user for the container has been created',
                'description': 'Containers should run as a non-root user.',
                'status': 'REVIEW',
                'reason': 'Package modifications executed as root user inside container.',
                'triggered_by': ['added', 'changed', 'removed']
            },
            {
                'id': '4.6',
                'title': 'Ensure that HEALTHCHECK instructions have been added to container images',
                'description': 'Add HEALTHCHECK to detect container health issues.',
                'status': 'REVIEW',
                'reason': 'Runtime dependency drift may affect container health checks.',
                'triggered_by': ['changed']
            },
            {
                'id': '5.7',
                'title': 'Ensure privileged ports are not mapped within containers',
                'description': 'Do not map privileged ports within containers.',
                'status': 'VIOLATED',
                'reason': 'Unauthorized package addition may expose privileged services.',
                'triggered_by': ['added']
            }
        ]
    },
    'NTIA_SBOM': {
        'name': 'NTIA Minimum Elements for SBOM',
        'version': 'EO 14028 — 2021',
        'controls': [
            {
                'id': 'ME.1',
                'title': 'Supplier Name',
                'description': 'SBOM must identify the supplier of each software component.',
                'status': 'COMPLIANT',
                'reason': 'Build-time SBOM includes supplier information via Syft and CycloneDX format.',
                'triggered_by': []
            },
            {
                'id': 'ME.6',
                'title': 'Dependency Relationships',
                'description': 'SBOM must capture relationships between components.',
                'status': 'VIOLATED',
                'reason': 'Runtime SBOM differs from build-time SBOM — dependency relationships are no longer accurate.',
                'triggered_by': ['added', 'changed', 'removed']
            },
            {
                'id': 'ME.7',
                'title': 'Author of SBOM Data',
                'description': 'SBOM must identify the entity that created the SBOM data.',
                'status': 'COMPLIANT',
                'reason': 'SBOM generated by Syft with CycloneDX format includes authorship metadata.',
                'triggered_by': []
            }
        ]
    },
    'CYCLONEDX': {
        'name': 'CycloneDX SBOM Standard',
        'version': 'v1.7',
        'controls': [
            {
                'id': 'CDX.1',
                'title': 'Component Inventory Accuracy',
                'description': 'SBOM must accurately reflect all software components in the system.',
                'status': 'VIOLATED',
                'reason': 'Runtime component inventory does not match build-time SBOM — drift detected.',
                'triggered_by': ['added', 'changed', 'removed']
            },
            {
                'id': 'CDX.2',
                'title': 'Vulnerability Association',
                'description': 'SBOM should include known vulnerability information for all components.',
                'status': 'PARTIAL',
                'reason': 'Grype vulnerability scan completed but runtime drift introduced unscanned packages.',
                'triggered_by': ['added']
            }
        ]
    }
}

STATUS_PRIORITY = {'VIOLATED': 0, 'REVIEW': 1, 'PARTIAL': 2, 'COMPLIANT': 3}

def evaluate_compliance(report):
    has_added = bool(report.get('added', {}))
    has_changed = bool(report.get('changed', {}))
    has_removed = bool(report.get('removed', {}))
    has_drift = has_added or has_changed or has_removed

    results = []
    summary = {'VIOLATED': 0, 'REVIEW': 0, 'PARTIAL': 0, 'COMPLIANT': 0}

    for framework_key, framework in COMPLIANCE_FRAMEWORK.items():
        framework_result = {
            'framework': framework['name'],
            'version': framework['version'],
            'key': framework_key,
            'controls': []
        }

        for control in framework['controls']:
            triggered = control['triggered_by']
            status = control['status']

            if triggered == ['any'] and not has_drift:
                status = 'COMPLIANT'
            elif not triggered:
                status = control['status']
            else:
                applicable = (
                    ('added' in triggered and has_added) or
                    ('changed' in triggered and has_changed) or
                    ('removed' in triggered and has_removed) or
                    triggered == ['any']
                )
                if not applicable:
                    status = 'COMPLIANT'

            summary[status] = summary.get(status, 0) + 1
            framework_result['controls'].append({
                'id': control['id'],
                'title': control['title'],
                'description': control['description'],
                'status': status,
                'reason': control['reason']
            })

        results.append(framework_result)

    overall = 'VIOLATED' if summary['VIOLATED'] > 0 else 'REVIEW' if summary['REVIEW'] > 0 else 'PARTIAL' if summary['PARTIAL'] > 0 else 'COMPLIANT'

    total = sum(summary.values())
    compliant_count = summary.get('COMPLIANT', 0) + summary.get('PARTIAL', 0) * 0.5
    compliance_score = int((compliant_count / total) * 100) if total > 0 else 0
    overall_label = 'Needs Remediation' if summary['VIOLATED'] > 0 else 'Needs Review' if summary['REVIEW'] > 0 else 'Partially Compliant' if summary['PARTIAL'] > 0 else 'Compliant'

    return results, summary, overall, compliance_score, overall_label

def save_compliance_report(results, summary, overall, compliance_score=0, overall_label=""):
    path = os.path.join(BASE_DIR, 'sbom', 'compliance-report.json')
    with open(path, 'w') as f:
        json.dump({
            'results': results,
            'summary': summary,
            'overall_status': overall,
            'compliance_score': compliance_score,
            'overall_label': overall_label
        }, f, indent=2)

if __name__ == '__main__':
    report_path = os.path.join(BASE_DIR, 'sbom', 'drift-report.json')
    with open(report_path) as f:
        report = json.load(f)

    results, summary, overall, score, label = evaluate_compliance(report)
    save_compliance_report(results, summary, overall, score, label)

    print(f"\nCompliance Assessment Complete")
    print(f"Overall Status: {overall} — {label}")
    print(f"Compliance Score: {score}%")
    print(f"Violated: {summary['VIOLATED']} | Review: {summary['REVIEW']} | Partial: {summary['PARTIAL']} | Compliant: {summary['COMPLIANT']}")
    print()
    for fw in results:
        print(f"  {fw['framework']}")
        for c in fw['controls']:
            print(f"    [{c['status']:10}] {c['id']} — {c['title']}")
